import {
  authorParamsGoogle,
  authorSchema,
  forgotPasswordParams,
  contentSchema,
  categorySchema,
  categoryParams,
  authorSchemaUpdate,
  authorParams,
  errorSchema,
  accountSchema,
  infoSchema,
  loginParams,
  noticePaginationSchema,
  noticeParams,
  noticeSchema,
  refreshTokenParams,
  refreshTokenSchema,
  resetPasswordParams,
} from './schemas/index';
export const schemas = {
  authorParams: authorParams,
  error: errorSchema,
  account: accountSchema,
  author: authorSchema,
  authorUpdate: authorSchemaUpdate,
  authorParamsGoogle: authorParamsGoogle,
  categoryParams: categoryParams,
  category: categorySchema,
  resetPasswordParams: resetPasswordParams,
  forgotPasswordParams: forgotPasswordParams,
  loginParams: loginParams,
  content: contentSchema,
  notice: noticeSchema,
  info: infoSchema,
  noticePagination: noticePaginationSchema,
  refreshTokenParams: refreshTokenParams,
  refreshToken: refreshTokenSchema,
  noticeParams: noticeParams,
};
